workspace(name = "cpp_pre_file")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_cc",
    urls = ["https://github.com/bazelbuild/rules_cc/archive/refs/tags/0.0.8.tar.gz"],
    strip_prefix = "rules_cc-0.0.8",
)
