workspace(name = "get_started")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_cc",
    urls = [
        "https://github.com/bazelbuild/rules_cc/releases/download/0.0.9/rules_cc-0.0.9.tar.gz",
    ],
    sha256 = "d0c2cf8e17826dfec66f64fdf75f1a4bb7a4484a1c2cc74e07bcb35c50a6481d",
)
