workspace(name = "boostorg_core")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# C++ rules (rules_cc)
http_archive(
    name = "rules_cc",
    sha256 = "9f3d0df8fd1e03df36e9a0975ae9003c2a0dc369e6a0eef8949cc0f9b867951a",
    strip_prefix = "rules_cc-0.0.8",
    urls = [
        "https://github.com/bazelbuild/rules_cc/archive/refs/tags/0.0.8.tar.gz",
    ],
)

load("@rules_cc//cc:repositories.bzl", "rules_cc_dependencies")

rules_cc_dependencies()
