workspace(name = "ryu")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Java rules (rules_java)
http_archive(
    name = "rules_java",
    urls = [
        "https://github.com/bazelbuild/rules_java/releases/download/7.7.0/rules_java-7.7.0.tar.gz",
    ],
    sha256 = "8e3034ba5513d8061c2a5ae049631b7d831bdb9fee9601b1517e0cf48d40c880",
)

load("@rules_java//java:repositories.bzl", "rules_java_dependencies", "rules_java_toolchains")

rules_java_dependencies()
rules_java_toolchains()
